config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  resources :feeds do
    collection do
      post :confirm
    end
  end

  resources :contacts
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users do
    collection do
      post :confirm
    end
  end
  resources :blogs do
    collection do
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
    validates :title, presence: true
    validates :content, length: { in: 1..140 }
    has_many :employees
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :require_sign_in!, only: [:new, :edit, :show]
 def index
    @blogs = Blog.all
 end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      @blog.image.retrieve_from_cache!  params[:cache][:image]
    else
      @blog = Blog.new
    end
  end

 def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id # login user がblog を投稿
    @blog.image.retrieve_from_cache!  params[:cache][:image]
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
      @inform = current_user.email
      ContactMailer.send_mail(@inform).deliver
    else
      render 'new'
    end


 end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id=current_user.id
    render :new if @blog.invalid?
  end


  private
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def set_user_infomation
      @user = User.find(params[:id])
    end

    def require_sign_in!
      unless logged_in?
        redirect_to sessions_new_path, noctice:"ログインしてください"
      end
    end
  end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<div class="blog_image">
    <p class="blog_image_lable"><%= form.label :image %></p>
    <p class="blog_image_input"><%= form.file_field :image, id: :@blog_image %></p>
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= form.hidden_field :image_cache %>
  </div>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
<% end %>

app/views/blogs/edit.html.erb
 <h2>ブログを編集する</h2>
  <%= render 'form' %>
  

app/views/blogs/index.html.erb
<h1>Listing Blogs</h1>
<div class="container">
  <div id="new-blog-link">
    <%= link_to '新規ブログを作成する', new_blog_path %>
  </div>

  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="blog-panel col-xs-12 col-md-6 ">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <div class="blog-links">
          <%=  link_to 'Show', blog, class: 'btn btn-default'  %>
          <% if current_user.id == blog.user_id %>
          <%=  link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %> |
          <%=  link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% else %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
  <h2>ブログを作成する</h2>
  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p class="show_blog_image">
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>