config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'

  resources :feeds do
    collection do
      post :confirm
    end
  end

  resources :contacts
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users do
    collection do
      post :confirm
    end
  end
  resources :blogs do
    collection do
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :icon_image, IconImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_infomation, only: [:edit, :update]

  def new
    if params[:back]
      @user = User.new(user_params)
      # @user.icon_image.retrieve_from_cache! params[:cache][:icon_image]
    else
      @user = User.new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end


  def create
    @user = User.new(user_params)
    if @user.save
      # redirect_to user_path(@user.id)
      redirect_to @user
    else
      # render 'new'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
    else
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:icon_image, :icon_image_cache)
  end
  def set_user_infomation
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
          confirm_users_path

      elsif action_name == 'edit'
          user_path

      end
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: user_choose_new_or_edit) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
   <p class="new_icon_lable"><%= form.label :icon_image %></p>
   <p class="new_icon_image"><%= form.file_field :icon_image, id: :@user_icon_image %></p>
   <%= image_tag(@user.icon_image.url) if @user.icon_image.url %>
   <%= form.hidden_field :icon_image_cache %>
 </div>
 <%= form.submit %>
<% end %>
<%= link_to "ユーザー詳細画面にもどる", user_path(@user.id) %>

app/views/users/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :password %>
  <%= form.hidden_field :password_confirmation %>
  <%= form.hidden_field :icon_image_cache %>

  <p>名前:<%= @user.name %></p>
  <p>メールアドレス:<%= @user.email %></p>
  <p>パスワード:<%= @user.password %></p>
  <p>
    <%= image_tag(@user.icon_image) %>
  </p>


  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :icon_image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h2>ユーザー情報を編集する</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, url: confirm_users_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <div class="new_icon">
          <p class="new_icon_lable"><  <%= f.label :icon_image %></p>
          <p class="new_icon_image"><%= f.file_field :icon_image, id: :@user_icon_image %></p>
          <%= image_tag(@user.icon_image) if @user.icon_image %>
          <%= f.hidden_field :icon_image_cache %>
        </div>


  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p class="user_infomation_image">
</p>
<p class="user_infomation">メールアドレス: <%= @user.email %></p>
<%= image_tag(@user.icon_image) if @user.icon_image %>
<p class="user_infomation">
  <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class: 'btn btn-warning' %>
</p>

 <h3>あなたのお気に入り投稿</h3><br>
 <div class="favrites">
  <% @favorite_blogs.each do |blog| %>
  <table>
    <tr>
      <h2><%= blog.title %></h2>
      <p><%= blog.content %></p>
      <p><%= blog.image %></p>

    </tr>
  </table>
   <% end %>
   <%= link_to "topにもどる", blogs_path %>
</div>